# SwiftLint Configuration for RIZQ iOS

disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
  - type_body_length
  - file_length
  - function_body_length

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional

excluded:
  - DerivedData
  - .build
  - Pods

force_cast: warning
force_try: warning

nesting:
  type_level: 3

reporter: "xcode"
