source "https://rubygems.org"

ruby ">= 3.0.0"

gem "fastlane"
gem "xcode-install"
gem "ostruct"  # Silence Ruby 3.5 deprecation warning

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
