name: RIZQ
options:
  bundleIdPrefix: com.rizq
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.2"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 2
  usesTabs: false

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "3"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 5SA6M6679W
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    SWIFT_STRICT_CONCURRENCY: minimal

configs:
  Debug:
    buildSettings:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
  Release:
    buildSettings:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
      SWIFT_OPTIMIZATION_LEVEL: "-O"

packages:
  # Pin swift-syntax to canonical URL to resolve identity conflicts
  SwiftSyntax:
    url: https://github.com/swiftlang/swift-syntax
    version: "600.0.1"
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    version: "1.17.0"
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: "1.0.0"
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: "1.0.0"
  Clocks:
    url: https://github.com/pointfreeco/swift-clocks
    from: "1.0.0"
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: "1.17.1"
  Nuke:
    url: https://github.com/kean/Nuke
    version: "12.8.0"
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"

targets:
  RIZQ:
    type: application
    platform: iOS
    sources:
      - path: RIZQ
        excludes:
          - "**/*.md"
    resources:
      - path: RIZQ/Resources
      - path: RIZQ/Assets.xcassets
      - path: RIZQ/PrivacyInfo.xcprivacy
    dependencies:
      - package: ComposableArchitecture
      - package: Dependencies
      - package: CasePaths
      - package: Clocks
      - package: Nuke
      - target: RIZQKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rizq.app
        INFOPLIST_FILE: RIZQ/Info.plist
        CODE_SIGN_ENTITLEMENTS: RIZQ/RIZQ.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        PRODUCT_NAME: RIZQ
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_TESTABILITY: YES
    preBuildScripts:
      - name: SwiftLint
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          fi
        basedOnDependencyAnalysis: false
    scheme:
      testTargets:
        - RIZQTests
        - RIZQSnapshotTests
      gatherCoverageData: true

  RIZQKit:
    type: framework
    platform: iOS
    sources:
      - path: RIZQKit
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: GoogleSignIn
        product: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rizq.app.kit
        INFOPLIST_FILE: RIZQKit/Info.plist
        DEFINES_MODULE: YES

  RIZQTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RIZQTests
    dependencies:
      - target: RIZQ
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rizq.app.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/RIZQ.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/RIZQ"
        BUNDLE_LOADER: "$(TEST_HOST)"

  RIZQSnapshotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RIZQSnapshotTests
    resources:
      - path: RIZQSnapshotTests/__Snapshots__
    dependencies:
      - target: RIZQ
      - package: SnapshotTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rizq.app.snapshottests
        INFOPLIST_FILE: RIZQSnapshotTests/Info.plist
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/RIZQ.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/RIZQ"
        BUNDLE_LOADER: "$(TEST_HOST)"

  RIZQWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: RIZQWidget
    dependencies:
      - target: RIZQKit
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rizq.app.widget
        INFOPLIST_FILE: RIZQWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: RIZQWidget/RIZQWidget.entitlements
        SKIP_INSTALL: YES

schemes:
  RIZQ:
    build:
      targets:
        RIZQ: all
        RIZQKit: [run, test]
        RIZQWidget: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: RIZQTests
          parallelizable: true
        - name: RIZQSnapshotTests
          parallelizable: false
    archive:
      config: Release
